
baseurl: ""
url: "https://azbukatriathlona.com"

# контакты
contacts:
  website: artissimo-school.ru
  phone: +7(985)247-76-40
  email:
  address: Москва, Борисоглебский Переулок 12
  social:
    instagram:
      url: https://www.instagram.com/artissimo_music_school/
      alt: Мой instagram
    vk:
      url: https://vk.com/id540304848
      alt: Вконтакте
#    youtube:
#      url:
#      alt: Мой канал на youtube

github: https://github.com/semenovem/static-site-music-school

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed

kramdown:
  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#  css_class: 'highlight'

#sass:
#  style: :expanded

# Exclude from processing.
exclude: [
  '.idea/',
  'node_modules', '_scripts', '_dev', '_plugins',
  'README.md', 'DEV_GUIDE.md',
  'gulpfile.js', 'package.json', 'package-lock.json', 'yarn.lock',
  'LICENSE', 'CNAME',
  '.editorconfig'
]

#collections_dir: _collections_

#collections:
#  albums:
#    output: false
#  videos:
#    output: false
#  music_tracks:
#    output: false
#  gallery:
#    output: false


defaults:
  - scope:
      type: albums
    values:
      nav_light: test

#  - scope:
#      path: ""
##      path: "*/index.html"
#    values:
#      yandexMetrika: true

# hash commit, for prevent caching file resource
short_hash_commit:

array: []

#end
